name: Update crontab on push

on:
  push:

jobs:
  setup-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Create and install cron job
        run: |
          echo "* * * * * echo 'Running cron job...' >> ~/cron-test.log" > mycron
          crontab mycron
          sudo service cron start
          echo "Cron job added:"
          crontab -l
