name: Simulate Dummy Cron on Push

on:
  push:
    branches:
      - master
  workflow_dispatch:  

jobs:
  dummy-cron-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Simulate Dummy Cron Task
        run: |
          NEW_CRON='0 19 * * * echo "Dummy cron executed at 7 PM" >> ~/dummy-cron.log'
          (crontab -l 2>/dev/null; echo "$NEW_CRON") | crontab -
          echo "Cron job added!"

      - name: Simulate Cron Execution Immediately
        run: |
          echo "Dummy cron executed at 7 PM" >> ~/dummy-cron.log    

      - name: Show Updated Crontab
        run: |
             crontab -l
             cat ~/dummy-cron.log

