name: Update crontab on push

on:
  push:

jobs:
  update-crontab:
    runs-on: ubuntu-latest
    steps:
      - name: Update crontab
        run: |
          crontab -e
          0 19 * * * echo "Dummy cron executed at 7 PM" >> ~/dummy-cron2.log
          echo "Cron job added!"
