name: Simulate Dummy Cron on Push

on:
  push:
    branches:
      - master

jobs:
  dummy-cron-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Simulate Dummy Cron Task
        run: |
          github.event.schedule = '30 5 * * 1,3'
          echo "Dummy cron executed at 7 pm" >> dummy-cron.log
          cat dummy-cron.log
