name: Simulate Dummy Cron on Push

on:
  #push:
   # branches:
    #  - master
  workflow_dispatch:  

jobs:
  dummy-cron-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add cron job on remote server
        run: |
          ssh sachi@172.23.75.112 '(
          crontab -l 2>/dev/null;
          echo "0 19 * * * echo "cron runs" >> /var/log/my-cron.log"
          ) | crontab -'
          echo "Cron job added!"

      - name: Simulate Cron Execution Immediately
        run: |
          echo "Dummy cron executed at 7 PM" >> ~/my-cron.log    

      - name: Show Updated Crontab
        run: |
             crontab -l
             cat ~/my-cron.log

