name: Lint Code (ESLint)

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Dependencies
        run: npm install

      - name: Grant execute permissions for ESLint
        run: chmod +x node_modules/.bin/eslint


      - name: Run ESLint
        run: npm run lint
