name: Unit Tests

on:
 # push:
  #  branches:
   #   - master
  pull_request:
    branches: [master]
  workflow_dispatch:  

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set execute permissions for Jest
        run: chmod +x node_modules/.bin/jest

      - name: Run Tests
        run: |
          npm install 
          npm test
