name: Conditional Scheduled Pipeline

on:
  push:
    branches:
      - main
      - master
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    concurrency:
      group: "deployment-lock"
      cancel-in-progress: true

    steps:  
      - name: wait for schedule time
        run: |
            TARGET_TIME="07:50"
            while [ "$(date -u +"%H:%M")" != "$TARGET_TIME" ]; do
            echo ""Waiting for $TARGET_TIME"
            sleep 60
            done
            echo "It's $TARGET_TIME , running the pipeline now..."

      - name: Run workflow
        run: echo "Pipeline runs successfully at scheduled time"      



