name: Scheduled Pipeline

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 22 * * *'  # Runs at 10 PM UTC daily

jobs:
  run_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run your script
        run: echo "Executing pipeline..."
