name: Conditional Scheduled Pipeline 

on:
  push:
    branches:
      - master
  schedule:
    - cron: '20 9 * * *'  # Runs at 10 PM UTC daily

jobs:
  run-pipeline:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: Check for push trigger
        run: |
          echo "Checking if a push happened today..."
          if [ "${{ github.event.before }}" == "0000000000000000000000000000000000000000" ]; then
            echo "No push detected. Skipping pipeline."
            exit 0
          fi
          echo "Push detected. Running pipeline..."
      
      - name: Execute pipeline
        run: echo "Executing scheduled pipeline..."
